### ISSUE TITLE
Missing SAP ABAP statements

### ISSUE THREAD

**Issue by SacrumDeus** [highlightjs/highlightjs-sap-abap#10]
I came up with some missing SAP ABAP statements such as

- EQUIV - https://help.sap.com/doc/abapdocu_751_index_htm/7.51/de-de/abenlogexp_equiv.htm
- IS BOUND - https://help.sap.com/doc/abapdocu_750_index_htm/7.50/de-de/abenlogexp_bound.htm
- IS ASSIGNED - https://help.sap.com/doc/abapdocu_750_index_htm/7.50/de-de/abenlogexp_assigned.htm
- IS SUPPLIED - https://help.sap.com/doc/abapdocu_750_index_htm/7.50/de-de/abenlogexp_supplied.htm
- IS INSTANCE OF - https://help.sap.com/doc/abapdocu_750_index_htm/7.50/de-de/abenlogexp_instance_of.htm
- VALUE #( ) - https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenconstructor_expression_value.htm
- COND #( ) - https://help.sap.com/doc/abapdocu_753_index_htm/7.53/en-US/abenconditional_expression_cond.htm
- CONV #( ) - https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenconstructor_expression_conv.htm
- CAST #( ) - https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenconstructor_expression_cast.htm

You can find a complete list of all SAP ABAP words right here:
https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-us/abenabap_words.htm

**Comment by larshp** [comment]
thanks, pull requests welcome

**Comment by SacrumDeus** [comment]
Added Pull Request
