### ISSUE TITLE
update grammar to the latest spec

### ISSUE THREAD

**Issue by larshp** [highlightjs/highlightjs-sap-abap#4]
see https://github.com/highlightjs/highlight.js/issues/3008

**Comment by marcellourbani** [comment]
will look into it after work

**Comment by mbtools** [comment]
I'm working on an update for monaco that covers up to 755. it's the most complete and comprehensive highlighter I'm aware of.  the attachment should help. 

[monaco-language-abap.zip](https://github.com/highlightjs/highlightjs-sap-abap/files/6068990/monaco-language-abap.zip)
